version: '3.1'

networks:
  play_the_game_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  mongo:
    image: mongo
    restart: always
    container_name: play_the_game_mongo
    ports:
      - 27017:27017
    networks:
      play_the_game_net:
        ipv4_address: 172.21.0.2

